In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
files = files.upload()

Saving book (1).csv to book (1).csv


In [10]:
book = pd.read_csv('book (1).csv',encoding='Latin1')
book

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [11]:
book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Unnamed: 0   10000 non-null  int64 
 1   User.ID      10000 non-null  int64 
 2   Book.Title   10000 non-null  object
 3   Book.Rating  10000 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 312.6+ KB


In [12]:
b1 = book.iloc[:,1:]
b1

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [15]:
b1.sort_values(['User.ID'])

User.ID                                         Book.Title  Book.Rating
2401        8                                              Wings            5
2400        8  The Western way: A practical guide to the West...            5
2399        8                            Ancient Celtic Romances            5
2402        8                                           Truckers            5
2405        8                                  The Art Of Celtia            7
...       ...                                                ...          ...
2395   278854      La crÃ³nica del PerÃº (CrÃ³nicas de AmÃ©rica)            7
2398   278854  Celtic Mythology (Library of the World's Myths...            8
2393   278854                         A corrente de Trewis Scott            7
2394   278854                                      As valkÃ­rias            7
2397   278854     A Treasury of Irish Myth, Legend, and Folklore            6

[10000 rows x 3 columns]

Unique elements in the data set

In [19]:
len(b1['User.ID'].unique())

2182

In [20]:
len(b1['Book.Title'].unique())

9659

pivoting the table

In [21]:
b2=b1.pivot_table(index='User.ID',columns='Book.Title',values='Book.Rating').reset_index(drop=True)
b2

Book.Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                            NaN                                         NaN   
1                            NaN                                         NaN   
2                            NaN                                         NaN   
3                            NaN                                         NaN   
4                            NaN                                         NaN   
...                          ...                                         ...   
2177                         NaN                                         NaN   
2178                         NaN                                         NaN   
2179                         NaN                                         NaN   
2180                         NaN                                         NaN   
2181                         NaN                                         NaN   

Book.Title   Repairing PC Drives &amp  '48  \
0                                 NaN  NaN   
1                                 NaN  NaN   
2                                 NaN  NaN   
3                                 NaN  NaN   
4                                 NaN  NaN   
...                               ...  ...   
2177                              NaN  NaN   
2178                              NaN  NaN   
2179                              NaN  NaN   
2180                              NaN  NaN   
2181                              NaN  NaN   

Book.Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                         NaN                       
1                                                         NaN                       
2                                                         NaN                       
3                                                         NaN                       
4                                                         NaN                       
...                                                       ...                       
2177                                                      NaN                       
2178                                                      NaN                       
2179                                                      NaN                       
2180                                                      NaN                       
2181                                                      NaN                       

Book.Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                         NaN              
1                                                         NaN              
2                                                         NaN              
3                                                         NaN              
4                                                         NaN              
...                                                       ...              
2177                                                      NaN              
2178                                                      NaN              
2179                                                      NaN              
2180                                                      NaN              
2181                                                      NaN              

Book.Title  01-01-00: A Novel of the Millennium  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
2177                                        NaN   
2178                                        NaN   
2179                                        NaN   
2180                                      

In [23]:
b2.index=b1['User.ID'].unique()
b2

Book.Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
276726                       NaN                                         NaN   
276729                       NaN                                         NaN   
276736                       NaN                                         NaN   
276737                       NaN                                         NaN   
276744                       NaN                                         NaN   
...                          ...                                         ...   
162107                       NaN                                         NaN   
162109                       NaN                                         NaN   
162113                       NaN                                         NaN   
162121                       NaN                                         NaN   
162129                       NaN                                         NaN   

Book.Title   Repairing PC Drives &amp  '48  \
276726                            NaN  NaN   
276729                            NaN  NaN   
276736                            NaN  NaN   
276737                            NaN  NaN   
276744                            NaN  NaN   
...                               ...  ...   
162107                            NaN  NaN   
162109                            NaN  NaN   
162113                            NaN  NaN   
162121                            NaN  NaN   
162129                            NaN  NaN   

Book.Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
276726                                                    NaN                       
276729                                                    NaN                       
276736                                                    NaN                       
276737                                                    NaN                       
276744                                                    NaN                       
...                                                       ...                       
162107                                                    NaN                       
162109                                                    NaN                       
162113                                                    NaN                       
162121                                                    NaN                       
162129                                                    NaN                       

Book.Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
276726                                                    NaN              
276729                                                    NaN              
276736                                                    NaN              
276737                                                    NaN              
276744                                                    NaN              
...                                                       ...              
162107                                                    NaN              
162109                                                    NaN              
162113                                                    NaN              
162121                                                    NaN              
162129                                                    NaN              

Book.Title  01-01-00: A Novel of the Millennium  \
276726                                      NaN   
276729                                      NaN   
276736                                      NaN   
276737                                      NaN   
276744                                      NaN   
...                                         ...   
162107                                      NaN   
162109                                      NaN   
162113                                      NaN   
162121                                    

In [25]:
b2.fillna(0,inplace=True)

Calculating Cosine Similarity between Users on array data

In [28]:
from sklearn.metrics import pairwise_distances
user_sim=1-pairwise_distances(b2.values,metric='cosine')
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
us2=pd.DataFrame(user_sim)
us2

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2177   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2178   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2179   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      2173  2174  2175  2176  2177  2178  2179  2180  2181  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2177   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  
2178   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
2179   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  

[2182 rows x 2182 columns]

In [30]:
us2.index=b1['User.ID'].unique()
us2.columns=b1['User.ID'].unique()
us2

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  ...  162085  162091  162092  162095  162103  162107  \
276726     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     1.0   
162109     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

        162109  162113  162121  162129  
276726     0.0     0.0     0.0     0.0  
276729     0.0     0.0     0.0     0.0  
276736     0.0     0.0     0.0     0.0  
276737     0.0     0.0     0.0     0.0  
276744     0.0     0.0     0.0     0.0  
...        ...     ...     ...     ...  
162107     0.0     0.0     0.0     0.0  
162109     1.0     0.0     0.0     0.0  
162113     0.0     1.0     0.0     0.0  
162121     0.0     0.0     1.0     0.0  
162129     0.0     0.0     0.0     1.0  

[2182 rows x 2182 columns]

Nullification

In [31]:
np.fill_diagonal(user_sim,0)
us2

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  ...  162085  162091  162092  162095  162103  162107  \
276726     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

        162109  162113  162121  162129  
276726     0.0     0.0     0.0     0.0  
276729     0.0     0.0     0.0     0.0  
276736     0.0     0.0     0.0     0.0  
276737     0.0     0.0     0.0     0.0  
276744     0.0     0.0     0.0     0.0  
...        ...     ...     ...     ...  
162107     0.0     0.0     0.0     0.0  
162109     0.0     0.0     0.0     0.0  
162113     0.0     0.0     0.0     0.0  
162121     0.0     0.0     0.0     0.0  
162129     0.0     0.0     0.0     0.0  

[2182 rows x 2182 columns]

Similar user

In [32]:
us2.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...  
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

Extract the books which userId 162109 & 276726 have watched

In [35]:
b1[(b1['User.ID']==162109) | (b1['User.ID']==276726)]

User.ID               Book.Title  Book.Rating
0      276726      Classical Mythology            5
9988   162109  The Flower in the Skull           10

In [36]:
b1[(b1['User.ID']==276729) | (b1['User.ID']==276726)]

User.ID            Book.Title  Book.Rating
0   276726   Classical Mythology            5
1   276729          Clara Callan            3
2   276729  Decision in Normandy            6

In [37]:
user_1=b1[(b1['User.ID']==276729)]
user_2=b1[(b1['User.ID']==276726)]

In [38]:
pd.merge(user_1,user_2,on='Book.Title',how='outer')

User.ID_x            Book.Title  Book.Rating_x  User.ID_y  Book.Rating_y
0   276729.0          Clara Callan            3.0        NaN            NaN
1   276729.0  Decision in Normandy            6.0        NaN            NaN
2        NaN   Classical Mythology            NaN   276726.0            5.0